### ISSUE TITLE
makensis

### ISSUE THREAD

**Issue by 2096779623** [termux/command-not-found#10]
~ $ makensis
No command makensis found, did you mean:
 Command makealias in package hunspell

https://github.com/termux/termux-packages/blob/master/packages/nsis/build.sh

`~ $ pkg i nsis
Hit:1 https://mirrors.ustc.edu.cn/termux/apt/termux-main stable InRelease
Hit:2 https://mirrors.ustc.edu.cn/termux/apt/termux-games games InRelease
Hit:3 https://mirrors.ustc.edu.cn/termux/apt/termux-science science InRelease
Hit:4 https://mirrors.ustc.edu.cn/termux/apt/termux-x11 x11 InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
nsis is already the newest version (3.08).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.`

`~ $ cd $PREFIX/opt/nsis
.../opt/nsis $ ls
makensis`

**Comment by Grimler91** [comment]
The command-not-found lists only contains commands that are in $PREFIX/bin, makensis is in $PREFIX/opt and is hence not included. @xtkoba what was the motivation behind putting it in $PREFIX/opt instead of $PREFIX/bin?

**Comment by 2096779623** [comment]
> The command-not-found lists only contains commands that are in $PREFIX/bin, makensis is in $PREFIX/opt and is hence not included. @xtkoba what was the motivation behind putting it in $PREFIX/opt instead of $PREFIX/bin?

I don't know.

[#9293](https://github.com/termux/termux-packages/pull/9293)

**Comment by xtkoba** [comment]
It was due to the build system not complying with FHS.
