### ISSUE TITLE
Auto-update command database with cron jobs

### ISSUE THREAD

**Issue by thunder-coding** [termux/command-not-found#13]
It should be possible to do this. The cron job can be run once a week. This should also help us ensure that our repository is consistent with termux-packages git repo

**Comment by thunder-coding** [comment]
It also seems like that this repo hasn't caught up with the new monorepo changes. Will have to do both in the same PR

**Comment by thunder-coding** [comment]
@Grimler91 what do you think of depending on apt's `Contents-<arch>.gz` for generating command-not-found database instead of downloading almost each deb and looking into it?

**Comment by Grimler91** [comment]
> what do you think of depending on apt's Contents-<arch>.gz for generating command-not-found database

Yeah that is a better idea for all of our aptly repos. We didn't have those content files when command-not-found was first written
