### ISSUE TITLE
update-command-not-found? 

### ISSUE THREAD

**Issue by Yisus7u7** [termux/command-not-found#5]
update-command-not-found is a utility for command-not-found to update the repositories that one has installed and synchronize them, apparently that command does not exist, has not been added or is not intended to be added?

**Comment by Grimler91** [comment]
Yepp, it has been a while. Code needs to be updated slightly to handle the new repositories

**Comment by Yisus7u7** [comment]
Tanks

**Comment by Grimler91** [comment]
Closing as an update has been released
