### ISSUE TITLE
Termux (command-not-found) still says "pkg install netcat"

### ISSUE THREAD

**Issue by emenotti** [termux/command-not-found#9]
Rename netcat to nmap-ncat

_Originally posted by @ghost in https://github.com/termux/termux-packages/issues/6921#issuecomment-850872043_

If one tries "nc" or "netcat", termux points to netcat, which has been renamed. Please remove or edit the suggestion.

**Comment by Grimler91** [comment]
The logic doesn't handle removal of subpackages, so that's something that needs to be fixed in the `[update_command_lists.sh](https://github.com/termux/command-not-found/blob/master/update_command_lists.sh)` script

**Comment by Grimler91** [comment]
Code has been updated so that it shouldn't happen again
